"""empty message

Revision ID: ff9148434139
Revises: 7831cfeb70b9
Create Date: 2019-05-12 13:45:40.128628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9148434139'
down_revision = '7831cfeb70b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    # ### end Alembic commands ###
